import { Link, usePage } from '@inertiajs/react';
import { useState, useEffect, useRef, type ReactNode } from 'react';
import BrandIdentity from './BrandIdentity';
import { useCopy } from '../content';
import type { Profile } from '../types';

export default function Layout({profile,active,children}:{profile:Profile|null;active:string;children:ReactNode}) {
 const home=useCopy('home'),art=useCopy('art'),teaching=useCopy('teaching'),about=useCopy('about'),contact=useCopy('contact');
 const navigation=[['/',home.menu_label],['/obra',art.menu_label],['/series','Series'],['/agenda','Agenda'],['/docencia',teaching.menu_label],['/docencia/materiales','Materiales docentes'],['/sobre-mi',about.menu_label],['/contacto',contact.menu_label]];
 const pathname=usePage().url.split('?')[0].split('#')[0];
 const current=pathname.startsWith('/series/')?'/series':navigation.some(([href])=>href===pathname)?pathname:active;
 const [open,setOpen]=useState(false);
 const menuButton=useRef<HTMLButtonElement>(null);
 const headerElement=useRef<HTMLElement>(null);
 useEffect(()=>{const header=headerElement.current;if(!header)return;const update=()=>document.documentElement.style.setProperty('--site-header-height',`${header.getBoundingClientRect().height}px`);update();const observer=new ResizeObserver(update);observer.observe(header);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);menuButton.current?.focus();}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[open]);const name=profile?.name||'Romina Elizabeth Jaimes';
 return <><a className="skip" href="#contenido">Ir al contenido</a><header ref={headerElement} className={open?'header site-header menu-open':'header site-header'}><Link href="/" className="brand" aria-label={`${name} · Inicio`}><BrandIdentity name={name} subtitle={profile?.brand_subtitle || 'ARTES VISUALES & DOCENCIA'}/></Link><button ref={menuButton} className="menu-toggle" aria-expanded={open} aria-controls="main-nav" onClick={()=>setOpen(!open)}>{open?'Cerrar ×':'Menú ☰'}</button><nav id="main-nav" className={open?'site-nav expanded':'site-nav'} aria-label="Principal">{navigation.map(([href,label])=><Link key={href} href={href} viewTransition onClick={()=>setOpen(false)} aria-current={current===href?'page':undefined}>{label}</Link>)}</nav></header><main key={active} id="contenido" className="page-content" data-section={active.slice(1) || 'inicio'} tabIndex={-1}>{children}</main><footer className="site-footer"><div className="footer-invitation"><div><span className="eyebrow">ARTE & ENCUENTRO</span><Link href="/contacto#mensaje" className="footer-title">Sigamos conversando.</Link></div><div className="footer-direct">{profile?.email&&<a href={`mailto:${profile.email}`}>{profile.email}</a>}{profile?.instagram&&<a href={profile.instagram}>Instagram</a>}<Link href="/contacto#mensaje" className="footer-write">Escribir una consulta <span aria-hidden="true">→</span></Link></div></div><div className="footer-colophon"><div className="footer-signature"><p>{name}</p><span>{profile?.footer_text||'Arte, aprendizaje y exploración.'}</span>{profile?.location&&<span>{profile.location}</span>}</div><nav className="footer-navigation" aria-label="Pie de página">{navigation.map(([href,label])=><Link key={href} href={href} viewTransition aria-current={current===href?'page':undefined}>{label}</Link>)}</nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {name}</span><a href="#contenido">Volver arriba</a><a href="/admin">Administración</a></div></footer></>;
}
